[package]
name = "flac_to_mp3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"
rayon = "1.11.0"
walkdir = "2.5.0"
